# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
addons:
  apt:
    packages:
    - imagemagick
    - tcl8.5
    - tk8.5
    - libcairo2
    - libavcodec-extra-53
    - libavdevice53
    - libavfilter2
    - libavformat53
    - libavutil-extra-51
    - libswscale2
matrix:
  include:
    - os: linux
      julia: 0.5
      sudo: false
    - os: linux
      julia: nightly
      sudo: false
    - os: osx
      julia: 0.5
    - os: osx
      julia: nightly
notifications:
  email: false
before_script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("VideoIO")'
script:
  # coverage=true causes tests to hang, see pull request #92
  - julia -e 'Pkg.test("VideoIO", coverage=false)'
