# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
julia:
  - 0.5
  - 0.6
  - nightly
matrix:	
  allow_failures:
    - julia: nightly
notifications:
  email: false
before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg imagemagick tcl8.5 tk8.5 libcairo2
# uncomment the following lines to override the default test script
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("VideoIO")'
  # coverage=true causes tests to hang, see pull request #92
  - if [ -f test/runtests.jl ]; then julia -e 'Pkg.test("VideoIO", coverage=false)'; fi
